apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-mon-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-mon-clusterrole
rules:
- apiGroups: [""]
  resources: ["events","pods"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-mon-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: event-mon-sa
roleRef:
  kind: ClusterRole
  name: event-mon-clusterrole
  apiGroup: rbac.authorization.k8s.io

