name: Build and Push Docker Image to Harbor

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: Monthome

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Display environment variables
        run: |
          echo "USER: $USER"
          echo "URL: $URL"
        env:
          USER: ${{ vars.USER }}
          URL: ${{ vars.URL }}
          
      - name: Login to Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ vars.URL }}
          username: ${{ vars.USER }}
          password: ${{ secrets.TOKEN }}

      # - name: Log in to Harbor
      #   run: echo "${{ secrets.TOKEN }}" | docker login "${{ env.URL }}" -u "${{ env.USER }}" --password-stdin
      #   env:
      #     USER: ${{ vars.USER }}
      #     URL: ${{ vars.URL }}
      #     TOKEN: ${{ secrets.TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.URL }}/utility/test:latest
