name: Build and Push Docker Image to Harbor

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: Monthome  # 환경 지정

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Display environment variables
        run: |
          echo "HARBOR_USER: $HARBOR_USER"
          echo "REPO_URL: $REPO_URL"
          echo "USER: $USER"
          echo "URL: $URL"
        env:
          HARBOR_USER: ${{ env.USER }}
          REPO_URL: ${{ env.URL }}
          USER: ${{ vars.USER }}
          URL: ${{ vars.URL }}

      - name: Log in to Harbor
        run: echo "${{ secrets.TOKEN }}" | docker login "${{ env.REPO_URL }}" -u "${{ env.HARBOR_USER }}" --password-stdin
        env:
          HARBOR_USER: ${{ env.USER }}
          REPO_URL: ${{ env.URL }}
          TOKEN: ${{ secrets.TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REPO_URL }}/test:latest
