name: Build and Push Docker Image to Harbor

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Harbor
        run: echo ${{ secrets.TOKEN }} | docker login ${{ env.REPO_URL }} -u ${{ env.HARBOR_USER }} --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REPO_URL }}/test:latest
