name: Build and Push Docker Image to Harbor

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    env:
      HARBOR_USER: ${{ env.HARBOR_USER }} # 환경 변수에서 직접 사용
      REPO_URL: ${{ env.REPO_URL }} # 환경 변수에서 직접 사용
      TOKEN: ${{ secrets.TOKEN }} # Secrets에서 토큰 사용

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Harbor
        run: echo $TOKEN | docker login $REPO_URL -u $HARBOR_USER --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: $REPO_URL/test:latest
